server:
  port: 10002
  servlet:
    context-path: /cloud

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      default-zone: http://127.0.0.1:8761
    fetch-registry: true
    register-with-eureka: true

spring:
  application:
    name: cloud-client

  datasource:
    url: jdbc:p6spy:mysql://47.107.121.157:3306/aibei2?serverTimezone=GMT%2B8
    username: aibei2
    password: aibei2
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver

mybatis-plus:
  type-aliases-package: com.liyaobing.springcloud.bean.*
  global-config:
    db-config:
      id-type: id_worker_str
      # 全局配置逻辑删除字段，应该使用bean的属性，而非sql列名
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
      table-prefix: abjy_tb_
      table-underline: true
  configuration:
    map-underscore-to-camel-case: true
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml